---
common: &common
  agents:
    - "capable_of_building=gdk-for-unreal"
    - "environment=production"
    - "permission_set=builder"
    - "platform=linux"  # if you need a different platform, configure this: macos|linux|windows.
    - "queue=${CI_LINUX_BUILDER_QUEUE:-v4-2019-12-12-bk5225-daecba805768d787}"
    - "scaler_version=2"
    - "working_hours_time_zone=london"

  timeout_in_minutes: 20
  retry:
    automatic:
        # This is designed to trap and retry failures because agent lost connection. Agent exits with -1 in this case.
      - exit_status: -1
        limit: 3

steps:
  # Stage 0: Tell Buildkite what you want to release.

  # TODO: I've modified gdk-version and added engine-version & preview. I need to call these keys using "buildkite-agent meta-data get" where required.
  - block: Configure your release.
    prompt: Fill out these details for your release.
    fields:
      - text: UnrealGDK component release version
        key: gdk-version
        required: true
        hint: The UnrealGDK component release version you want to create a release candidate for, e.g. - 0.1.2 or 1.0.1.
        
      - select: "Unreal Engine version(s)"
        key: "engine-version"
        hint: "The Unreal Engine version(s) you want to branch a release candidate from, e.g. - 4.24-SpatialOSUnrealGDK"
        required: true
        multiple: true
        # When multiple options are selected, they are delimited in the meta-data field by a line break (\n). prepare=release.sh then turns this into a list of comma seperated values.
        # TODO: Note in the WIP Maintainers Guide (UNR-2648) that you have to update these defaults and optione when you introduce a new engine branch. Even better, have a regex pull these branches by recognising the format.
        default:
          - "4.24-SpatialOSUnrealGDK"
          - "4.23-SpatialOSUnrealGDK"
        options:
          - label: "4.24-SpatialOSUnrealGDK"
            value: "4.24-SpatialOSUnrealGDK"
          - label: "4.23-SpatialOSUnrealGDK"
            value: "4.23-SpatialOSUnrealGDK"

      - select: "Preview release?"
        key: "preview"
        hint: "If this is a preview release, press the preview button."
        required: false
        options:
          - label: "preview"
            value: "preview"

  # Stage 1: Prepare the release candidates.

  # There is one prepare step for each repo we release.
  # Prepare steps create a PR and upload metadata but do not release anything.
  - label: Prepare the UnrealGDK release
    command: ci/prepare-release.sh UnrealGDK
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    retry:
      manual:
        permit_on_passed: true

  - label: Prepare UnrealGDKExampleProject release
    command: ci/prepare-release.sh UnrealGDKExampleProject
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    retry:
      manual:
        permit_on_passed: true

  - label: Prepare UnrealGDKTestGyms release
    command: ci/prepare-release.sh UnrealGDKTestGyms
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    retry:
      manual:
        permit_on_passed: true

  # TODO: Re-write prepare-release.sh to work with our Engine branching strategy and multiple engines.
  - label: Prepare UnrealEngine release
    command: ci/prepare-release.sh UnrealEngine
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    retry:
      manual:
        permit_on_passed: true

  - wait
  # Stage 2: Run all tests against the release candidates.
  # TODO: Work out what generate-release-qa-trigger.sh does and re-write it to run all tests across all four repos.
  - label: "Add step for triggering release QA"
    command: ci/generate-release-qa-trigger.sh UnrealGDK | buildkite-agent pipeline upload
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    retry:
      manual:
        permit_on_passed: true

  # Stage 3: Promote the release candiates to preview and/or relase branches.

  # Block steps require a human to click a button, this is a safety precaution.
  - block: Unblock UnrealGDK release

  # TODO: Re-write release.sh to function across all four repos.
  - label: Release UnrealGDK
    command: ci/release.sh UnrealGDK
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
